// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVzECjtGyUktnrOqgkrP-imtDYgt98E9o',
    appId: '1:50335156864:web:caf1b7b983669479a27465',
    messagingSenderId: '50335156864',
    projectId: 'news-api-v2',
    authDomain: 'news-api-v2.firebaseapp.com',
    storageBucket: 'news-api-v2.appspot.com',
    measurementId: 'G-XK2QBT6FHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqo5L3y6tkhzzMdXaW5WN7h_Uk9O6r2Ck',
    appId: '1:50335156864:android:f27e41864b208f5fa27465',
    messagingSenderId: '50335156864',
    projectId: 'news-api-v2',
    storageBucket: 'news-api-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPlO66x4KHW0kMiZepV0u4Y_-nYk2zUUs',
    appId: '1:50335156864:ios:aed7fcf7e8d95b8ba27465',
    messagingSenderId: '50335156864',
    projectId: 'news-api-v2',
    storageBucket: 'news-api-v2.appspot.com',
    iosBundleId: 'com.newswave.newApiV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPlO66x4KHW0kMiZepV0u4Y_-nYk2zUUs',
    appId: '1:50335156864:ios:aed7fcf7e8d95b8ba27465',
    messagingSenderId: '50335156864',
    projectId: 'news-api-v2',
    storageBucket: 'news-api-v2.appspot.com',
    iosBundleId: 'com.newswave.newApiV2',
  );
}
